# -*- coding: utf-8 -*-
"""sdaia_assignment2ph2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRWrWlfKj_3zASbjPqJZgujQ9ZSI5pyM
"""

!pip install -q google-genai faiss-cpu

from google import genai
import faiss
import numpy as np
import json

client = genai.Client(api_key="API_KEY_HERE")

# Load the FAISS database

index = faiss.read_index(
    "places_faiss.index"
)

print("Number of vectors:", index.ntotal)

# Load chunk metadata

with open("chunks_metadata.json", "r", encoding="utf-8") as file:

    all_chunks = json.load(file)

print("Number of chunks:", len(all_chunks))

# Define the RAG function

def ask_question(question, top_k=3):

    print("\n================================")
    print("QUESTION")
    print("================================")
    print(question)

    # Convert question into embedding

    query_result = client.models.embed_content(
        model="gemini-embedding-2",
        contents=question
    )

    query_vector = np.array(
        [query_result.embeddings[0].values],
        dtype="float32"
    )

    # Normalize query vector

    faiss.normalize_L2(query_vector)

    # Search the vector database

    scores, indices = index.search(
        query_vector,
        top_k
    )

    print("\n================================")
    print("TOP RELEVANT CHUNKS")
    print("================================")

    retrieved_chunks = []
    references = []

    for rank, (score, idx) in enumerate(
        zip(scores[0], indices[0]), 1
    ):

        chunk = all_chunks[idx]

        print(f"\n--- Result {rank} ---")
        print(f"Cosine Similarity: {score:.4f}")
        print(f"Source: {chunk['file_name']}")
        print("Text:")
        print(chunk["text"])

        retrieved_chunks.append(chunk["text"])

        if chunk["file_name"] not in references:
            references.append(chunk["file_name"])

    # Combine retrieved chunks

    context = "\n\n".join(
        retrieved_chunks
    )

    # Build the LLM prompt

    prompt = f"""
You are a question-answering assistant.

Answer the user's question using ONLY the provided context.

Context:
{context}

User Question:
{question}

Instructions:
- Use only the information in the context.
- Do not add information from outside the context.
- Give the answer directly and briefly.
- If the context does not contain enough information,
  say: "I don't have enough information to answer this."
"""

    # Generate the final answer

    response = client.models.generate_content(
        model="gemini-3.1-flash-lite",
        contents=prompt
    )

    # Print final output

    print("\n================================")
    print("FINAL OUTPUT")
    print("================================")

    print("\nUser Question:")
    print(question)

    print("\nGenerated Answer:")
    print(response.text)

    print("\nReferences:")

    for reference in references:
        print(f"- {reference}")

    return response.text

# Test a city question

answer = ask_question(
    "What is AlUla famous for?"
)

# Test a project question

answer = ask_question(
    "Which project focuses on entertainment, sports, culture, and tourism?"
)