# -*- coding: utf-8 -*-
"""sdaia_assignment2ph1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LejUAop_pO8kMjyuuBTaYVCFrLf1HkCq
"""

!pip install -q google-genai faiss-cpu

from google import genai
import faiss
import numpy as np
import re
import json

client = genai.Client(api_key="API_KEY_HERE")

#read the text files
file_names = [
    "Saudi Projects & Vision 2030.txt",
    "Saudi Tourism.txt",
    "Saudi heritage and culture.txt"
]

documents = []

for file_name in file_names:

    with open(file_name, "r", encoding="utf-8") as file:
        text = file.read()

    documents.append({
        "file_name": file_name,
        "text": text
    })

    print(f"{file_name}: {len(text)} characters")

#Dynamic chunking
def dynamic_chunking(text, max_chars=700):

    paragraphs = [
        p.strip()
        for p in text.split("\n")
        if p.strip()
    ]

    chunks = []
    current_chunk = ""

    for paragraph in paragraphs:

        sentences = re.split(r'(?<=[.!?])\s+', paragraph)

        for sentence in sentences:

            sentence = sentence.strip()

            if not sentence:
                continue

            if len(current_chunk) + len(sentence) + 1 <= max_chars:

                if current_chunk:
                    current_chunk += " " + sentence
                else:
                    current_chunk = sentence

            else:

                if current_chunk:
                    chunks.append(current_chunk)

                current_chunk = sentence

    if current_chunk:
        chunks.append(current_chunk)

    return chunks

# Create chunks with file references
all_chunks = []

for document in documents:

    file_name = document["file_name"]
    text = document["text"]

    chunks = dynamic_chunking(
        text,
        max_chars=700
    )

    for chunk in chunks:

        all_chunks.append({
            "text": chunk,
            "file_name": file_name
        })

print("Total chunks:", len(all_chunks))

#print chunks
for i, chunk in enumerate(all_chunks):

    print(f"\n--- Chunk {i + 1} ---")
    print("Source:", chunk["file_name"])
    print("Characters:", len(chunk["text"]))
    print(chunk["text"])

#Count tokens in each chunk
token_counts = []

for i, chunk in enumerate(all_chunks):

    result = client.models.count_tokens(
        model="gemini-3.8-flash",
        contents=chunk["text"]
    )

    token_counts.append(result.total_tokens)

    print(
        f"Chunk {i + 1} ({chunk['file_name']}): "
        f"{result.total_tokens} tokens"
    )

#Embeddings
embeddings = []

for i, chunk in enumerate(all_chunks):

    result = client.models.embed_content(
        model="gemini-embedding-2",
        contents=chunk["text"]
    )

    vector = result.embeddings[0].values

    embeddings.append(vector)

    print(
        f"Chunk {i + 1} from {chunk['file_name']} "
        f"→ Vector size: {len(vector)}"
    )
#Transform the emmbidings into numpy
embedding_matrix = np.array(
    embeddings,
    dtype="float32"
)

print("Embedding matrix shape:", embedding_matrix.shape)

# Build FAISS cosine similarity index

faiss.normalize_L2(embedding_matrix)

dimension = embedding_matrix.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(embedding_matrix)

print("Number of vectors in FAISS:", index.ntotal)

# Save FAISS vector database

faiss.write_index(
    index,
    "places_faiss.index"
)

print("FAISS database saved successfully")

# Save chunk metadata

with open("chunks_metadata.json", "w", encoding="utf-8") as file:

    json.dump(
        all_chunks,
        file,
        ensure_ascii=False,
        indent=4
    )

print("Metadata saved successfully")