# -*- coding: utf-8 -*-
"""sdaia_assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGor6tTUp7TqF_1-JkazDNQJLgU9VFeG
"""

!pip install -q google-genai

#Tokenization
from google import genai

client = genai.Client(api_key="API_KEY_HERE")

with open("Saudi Projects & Vision 2030.txt", "r", encoding="utf-8") as file:
    text = file.read()

# Chunking with 20% character overlap
words = text.split()

chunk_size = 500
overlap = 100
step = chunk_size - overlap

chunks = []

for i in range(0, len(text), step):
    chunk = text[i:i + chunk_size]

    if chunk:
        chunks.append(chunk)

print("Number of chunks:", len(chunks))

for i, chunk in enumerate(chunks):
    print(f"\n--- Chunk {i+1} ---")
    print(f"Characters: {len(chunk)}")
    print(chunk)

#Tokenization
for i, chunk in enumerate(chunks):
    result = client.models.count_tokens(
        model="gemini-3.5-flash-lite",
        contents=chunk
    )

    print(f"Chunk {i+1}: {result.total_tokens} tokens")

#Embeddings
embeddings = []

for chunk in chunks:

    result = client.models.embed_content(
        model="gemini-embedding-001",
        contents=chunk
    )

    embeddings.append(result.embeddings[0].values)

print("Number of embeddings:", len(embeddings))

#Victors
for i, (chunk, vector) in enumerate(zip(chunks, embeddings)):
    print(f"\n--- Chunk {i+1} ---")
    print(chunk)

    print("\nVector:")
    print(vector)

#Semantic Similarity Search + Answer
from sklearn.metrics.pairwise import cosine_similarity

def ask_question(question, top_k=3):

    # Convert the question into an embedding
    query_result = client.models.embed_content(
        model="gemini-embedding-001",
        contents=question
    )

    query_vector = query_result.embeddings[0].values

    # Calculate cosine similarity
    similarities = cosine_similarity(
        [query_vector],
        embeddings
    )[0]

    # Get top 3 chunks
    top_indices = similarities.argsort()[-top_k:][::-1]

    print("\nQuestion:")
    print(question)

    print("\nTop 3 Most Relevant Chunks:")

    for rank, index in enumerate(top_indices, 1):
        print(f"\n--- Rank {rank} ---")
        print(f"Similarity Score: {similarities[index]:.4f}")
        print(f"Chunk {index + 1}:")
        print(chunks[index])

    # Combine retrieved chunks
    context = "\n\n".join(
        chunks[index] for index in top_indices
    )

    # Generate final answer
    prompt = f"""
Answer the question using ONLY the information in the context.

Context:
{context}

Question:
{question}

If the answer is not available in the context, say:
"I don't have enough information to answer this."
"""

    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )

    print("\nAnswer:")
    print(response.text)

#Question
ask_question("What is The Line?")